import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as THREE from './vendor/three-r180/three.module.min.js';
import {setupNativeGeometryTransport,traceNativeGeometryRay,replaceNativeRefraction,removeOpticalPrimaryShadowCalls,nativeTransportGLSL,nativeTransportPathGLSL} from './instrument-native-geometry-transport.mjs';
const source=(await readFile(new URL('./vendor/three-mesh-bvh-0.9.5/index.module.js',import.meta.url),'utf8')).replace("from 'three'",`from '${new URL('./vendor/three-r180/three.module.min.js',import.meta.url).href}'`);
const bvhLibrary=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const close=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),identity=()=>new THREE.Matrix4();

function slabs(){const entries=[{module:0,id:1,lo:0,hi:10},{module:1,id:1,lo:20,hi:22},{module:1,id:2,lo:22.2,hi:32.2}];return{contains(p,module,id){return entries.some(e=>e.module===module&&e.id===id&&p[2]>e.lo&&p[2]<e.hi);},nextOpticalEvent(ro,rd,{module,minDistance,maxDistance}){let result=null;for(const e of entries.filter(e=>e.module===module))for(const [z,normal]of[[e.lo,[0,0,-1]],[e.hi,[0,0,1]]]){const distance=(z-ro[2])/rd[2];if(distance>minDistance&&distance<maxDistance&&(!result||distance<result.distance))result={distance,point:ro.map((v,i)=>v+rd[i]*distance),normal,solidId:e.id,primitiveId:e.id,entering:normal[2]*rd[2]<0};}return result;}};}
function plane(z,name='native opaque plate'){return{intersectRay(ro,rd,{minDistance,maxDistance}){const distance=(z-ro[2])/rd[2];return distance>minDistance&&distance<maxDistance?{distance,point:ro.map((v,i)=>v+rd[i]*distance),object:{name},materialId:0}:null;}};}
const media=[{ior:1.52,sigma:[.01,.02,.03]},{ior:1,sigma:[0,0,0]},{ior:1.52,sigma:[.01,.02,.03]},{ior:1.333,sigma:[.04,.05,.06]}];
const trace=(atlas,extra={})=>traceNativeGeometryRay({kernel:slabs(),atlas,world:[identity(),identity()],inverse:[identity(),identity()],media,origin:[0,0,-5],direction:[0,0,1],...extra});

test('both aligned optical modules are crossed in order and every Fresnel interface is counted once',()=>{
 const result=trace(plane(40));assert.equal(result.opaqueHit.object.name,'native opaque plate');assert.deepEqual(result.events.map(e=>e.id),[1,1,3,3,4,4]);assert.deepEqual(result.events.map(e=>e.entering),[true,false,true,false,true,false]);assert.equal(result.exhausted,false);
 const fg=((1.52-1)/(1.52+1))**2,fw=((1.333-1)/(1.333+1))**2,factor=(1-fg)**4*(1-fw)**2;for(let k=0;k<3;k++)close(result.weight[k],factor*Math.exp(-media[0].sigma[k]*12-media[3].sigma[k]*10),1e-10);
});
test('real enclosed opaque hardware terminates before the back water/glass surface and absorbs only the traveled medium interval',()=>{
 const result=trace(plane(27,'hidden interior hardware'));assert.equal(result.opaqueHit.object.name,'hidden interior hardware');assert.deepEqual(result.events.map(e=>e.id),[1,1,3,3,4]);close(result.point[2],27);const factor=result.events.reduce((value,e)=>value*(1-e.fresnel),1);for(let k=0;k<3;k++)close(result.weight[k],factor*Math.exp(-media[0].sigma[k]*12-media[3].sigma[k]*4.8),1e-10);
});
test('TIR retains medium membership, direction and energy until a real hit or explicit bounded exhaustion',()=>{
 const zeroMedia=media.map(m=>({...m,sigma:[0,0,0]})),result=trace({intersectRay:()=>null},{origin:[0,0,5],direction:[Math.sqrt(.75),0,.5],media:zeroMedia,maxInterfaces:4});assert.equal(result.exhausted,true);assert.equal(result.events.length,4);assert.ok(result.events.every(e=>e.tir&&e.iorI===1.52&&e.iorT===1));assert.deepEqual(result.weight,[1,1,1]);assert.ok(result.events.every(e=>e.fresnel===1));
});
test('native binder preserves expanded transmission ABI and removes all primary stock shadow calls',()=>{
 const original=THREE.ShaderChunk.transmission_pars_fragment.replaceAll('transmissionSamplerMap','workingTransmissionMap').replaceAll('transmissionSamplerSize','workingTransmissionSize');const rewritten=replaceNativeRefraction(original,nativeTransportGLSL()+nativeTransportPathGLSL());assert.equal((rewritten.match(/vec4\s+getIBLVolumeRefraction\s*\(/g)??[]).length,1);const body=rewritten.slice(rewritten.indexOf('vec4 getIBLVolumeRefraction'));assert.ok(!body.includes('getTransmissionSample'));assert.match(body,/cadNativeTransport/);assert.ok(!body.includes('EnvironmentBRDF'));assert.throws(()=>replaceNativeRefraction(original.replaceAll('attenuationDistance','alteredDistance'),' '),/ABI/);
 const lights=removeOpticalPrimaryShadowCalls('#include <lights_fragment_begin>',THREE.ShaderChunk.lights_fragment_begin);assert.ok(!/\bget(?:Point)?Shadow\s*\(/.test(lights));assert.match(nativeTransportGLSL(),/cadNativeShadowMap/);assert.throws(()=>removeOpticalPrimaryShadowCalls('invalid','invalid'),/shadow ABI/);
});

test('actual native coefficients combine with opaque CAD, finite source lighting, refreshed shadows and owned resource disposal',async()=>{
 const recipe=JSON.parse(await readFile(new URL('./assets/instrument-optical-primitives-v1/primitives.json',import.meta.url),'utf8')),bytes=await readFile(new URL('./assets/instrument-optical-primitives-v1/native-water-cable-boundary.bin',import.meta.url)),buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),header=new Uint32Array(buffer,0,4),ductGeometry=new THREE.BufferGeometry();ductGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buffer,16,header[1]*3).slice(),3));ductGeometry.setAttribute('normal',new THREE.BufferAttribute(new Float32Array(buffer,16+header[1]*12,header[1]*3).slice(),3));ductGeometry.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,16+header[1]*24,header[2]*3).slice(),1));
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(),glass=new THREE.MeshPhysicalMaterial({ior:1.52}),waterMaterial=new THREE.MeshPhysicalMaterial({ior:1.333}),opaqueMaterial=new THREE.MeshPhysicalMaterial({color:0x777777});glass.userData.cadTransmission=1;waterMaterial.userData.cadTransmission=1;const lens=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),glass),shell=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),glass),water=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),waterMaterial),plate=new THREE.Mesh(new THREE.BoxGeometry(2,50,40),opaqueMaterial);lens.name='light/lens';lens.position.x=-120;shell.name='elements/glass';water.name='elements/water';water.userData.staticWater=true;plate.name='actual aft CAD plate';scene.add(lens,shell,water,plate);
 const key=new THREE.DirectionalLight(0xfffaf0,3);key.position.set(30,-20,40);key.castShadow=true;scene.add(key,key.target);const textures=Object.fromEntries(['color','normal','surface'].map(name=>[name,new THREE.DataArrayTexture(new Uint8Array([128,128,255,255]),1,1,1)])),arrays={textures,layerLookup:new Map(),wearLayerLookup:new Map()},module=await setupNativeGeometryTransport({THREE,scene,objects:[lens,shell,water,plate],camera,size:{value:new THREE.Vector2(640,360)},paperColor:new THREE.Color(.8,.8,.8),arrays,primitives:recipe,ductGeometry,bvhLibrary,yieldBuild:async()=>{}});
 const hit=module.traceRay('light',[-160,10,0],[1,0,0]);assert.equal(hit.opaqueHit?.object,plate);assert.ok(hit.events.some(e=>e.id===1));assert.ok(hit.events.some(e=>e.id===3));assert.ok(hit.events.some(e=>e.id===4));assert.equal(hit.exhausted,false);assert.equal(module.snapshot().geometry.ductTriangles,5736);
 const shader={uniforms:{},fragmentShader:THREE.ShaderLib.physical.fragmentShader};assert.equal(module.bindShader(shader,glass,'scenes'),false);assert.equal(module.bindShader(shader,glass,'light'),true);for(const name of['cadPbrKeyColor','cadPbrFillColor','cadPbrKeyDirection'])assert.ok(shader.uniforms[name].value.toArray().every(Number.isFinite));close(shader.uniforms.cadPbrKeyColor.value.x,key.color.r*key.intensity);assert.equal(shader.uniforms.cadNativeHasShadow.value,false);
 const shadowTexture=new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1);key.shadow.map={texture:shadowTexture};module.update(camera);assert.equal(shader.uniforms.cadNativeHasShadow.value,true);assert.equal(shader.uniforms.cadNativeShadowMap.value,shadowTexture);assert.equal(module.snapshot().nativeKeyShadow,true);
 let disposed=0;for(const[name,uniform]of Object.entries(shader.uniforms))if(name.startsWith('cadHit'))uniform.value.addEventListener('dispose',()=>disposed++);let sourceDispose=0;ductGeometry.addEventListener('dispose',()=>sourceDispose++);module.dispose();module.dispose();assert.equal(disposed,9);assert.equal(sourceDispose,0);assert.equal(module.snapshot().disposed,true);
 const specialized=await setupNativeGeometryTransport({THREE,scene,objects:[lens,shell,water,plate],camera,size:{value:new THREE.Vector2(640,360)},paperColor:new THREE.Color(.8,.8,.8),arrays,primitives:recipe,ductGeometry,bvhLibrary,yieldBuild:async()=>{},specializeCapture:true}),mainShader={uniforms:{},fragmentShader:THREE.ShaderLib.physical.fragmentShader},captureShader={defines:{CAD_TRANSPORT_CAPTURE:1},uniforms:{},fragmentShader:THREE.ShaderLib.physical.fragmentShader};specialized.bindShader(mainShader,glass,'light');specialized.bindShader(captureShader,glass,'light');assert.ok(!mainShader.fragmentShader.includes('CadGeometryHit'));assert.ok(!Object.hasOwn(mainShader.uniforms,'cadHitPositions'));assert.match(captureShader.fragmentShader,/CadGeometryHit/);assert.ok(captureShader.uniforms.cadHitPositions.value.isDataTexture);assert.deepEqual(specialized.snapshot().textureSamplers,{capture:15,main:2});assert.equal(specialized.snapshot().geometry.maxTlasDepth,1);assert.equal(specialized.snapshot().geometry.tlasStackDepth,0);specialized.dispose();assert.equal(sourceDispose,0);
 for(const texture of Object.values(textures))texture.dispose();shadowTexture.dispose();ductGeometry.dispose();
});
