import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as THREE from './vendor/three-r180/three.module.min.js';
import {createNativeHitGeometry as createNativeHitGeometryRuntime,encodeHitNormal,decodeHitNormal,nativeHitGeometryGLSL,intersectHitTriangleFloat32} from './instrument-native-hit-geometry.mjs';
import {nativeDielectric} from './instrument-analytic-optics.mjs';
const librarySource=(await readFile(new URL('./vendor/three-mesh-bvh-0.9.5/index.module.js',import.meta.url),'utf8')).replace("from 'three'",`from '${new URL('./vendor/three-r180/three.module.min.js',import.meta.url).href}'`);
const library=await import('data:text/javascript;base64,'+Buffer.from(librarySource).toString('base64'));
const createNativeHitGeometry=options=>createNativeHitGeometryRuntime({...options,bvhLibrary:library});
const close=(a,b,tolerance=1e-6)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`);
test('optional real optical boundary classes preserve opaque materials and select exact optical media',async()=>{
 const scene=new THREE.Scene(),opaque=new THREE.MeshPhysicalMaterial(),glass=new THREE.MeshPhysicalMaterial({ior:1.52});glass.userData.cadTransmission=1;
 const plate=new THREE.Mesh(new THREE.BoxGeometry(2,2,2),opaque),lens=new THREE.Mesh(new THREE.BoxGeometry(2,2,2),glass),shell=new THREE.Mesh(new THREE.BoxGeometry(2,2,2),glass),water=new THREE.Mesh(new THREE.BoxGeometry(2,2,2),glass);
 lens.position.x=5;shell.position.x=10;water.position.x=15;scene.add(plate,lens,shell,water);const objects=[plate,lens,shell,water];
 const baseline=await createNativeHitGeometry({THREE,scene,objects,yieldBuild:async()=>{}}),atlas=await createNativeHitGeometry({THREE,scene,objects,opticalObjects:[{object:lens,classTag:3},{object:shell,classTag:5},{object:water,classTag:6}],yieldBuild:async()=>{}});
 assert.deepEqual(atlas.materials,baseline.materials);assert.deepEqual(atlas.snapshot().opticalClasses,[3,5,6]);assert.equal(atlas.snapshot().opticalTriangles,36);
 assert.equal(atlas.intersectRay([-5,0,0],[1,0,0]).object,plate);assert.equal(atlas.intersectRay([2,0,0],[1,0,0],{classFilter:2}).object,lens);
 for(const [object,tag]of[[lens,3],[shell,5],[water,6]]){const hit=atlas.intersectRay([2,0,0],[1,0,0],{classFilter:tag});assert.equal(hit.object,object);assert.equal(hit.classTag,tag);const inside=atlas.intersectRay(object.position.toArray(),[0,1,0],{classFilter:tag,minDistance:1e-7,maxDistance:100});assert.ok(inside.geometricNormal[1]>0);}
 assert.match(nativeHitGeometryGLSL(atlas),/classFilter==2\?0xfffffffcu/);baseline.dispose();atlas.dispose();for(const object of objects)object.geometry.dispose();opaque.dispose();glass.dispose();
});
function fixture(){const scene=new THREE.Scene(),a=new THREE.MeshPhysicalMaterial({color:0x808080}),b=new THREE.MeshPhysicalMaterial({color:0xff0000}),glass=new THREE.MeshPhysicalMaterial({ior:1.52});glass.userData.cadTransmission=1;
 const objects=[new THREE.Mesh(new THREE.BoxGeometry(4,6,8),a),new THREE.Mesh(new THREE.SphereGeometry(3,12,8),b),new THREE.Mesh(new THREE.BoxGeometry(2,3,4),[a,b,a,b,a,b]),new THREE.Mesh(new THREE.SphereGeometry(6),glass)];objects[0].position.set(-7,0,0);objects[1].position.set(6,2,-4);objects[2].position.set(0,-5,3);objects[2].rotation.set(.2,.4,-.3);objects[2].scale.set(.8,1.4,1.1);objects[3].position.z=15;scene.add(...objects);
 const duct=new THREE.Mesh(new THREE.CylinderGeometry(1,1,8,16),a);duct.position.set(0,6,0);scene.add(duct);return{scene,objects,a,b,glass,duct};}
function brute(objects,origin,direction,min=.001,max=Infinity){const ray=new THREE.Ray(new THREE.Vector3(...origin),new THREE.Vector3(...direction));let nearest=null;for(const object of objects){if(!object.visible)continue;const geometry=object.geometry,position=geometry.attributes.position,index=geometry.index;for(let i=0;i<(index?.count??position.count);i+=3){const points=Array.from({length:3},(_,k)=>new THREE.Vector3().fromBufferAttribute(position,index?index.getX(i+k):i+k).applyMatrix4(object.matrixWorld)),point=ray.intersectTriangle(...points,false,new THREE.Vector3());if(!point)continue;const distance=point.distanceTo(ray.origin);if(distance>min&&distance<max){max=distance;nearest={distance,point:point.toArray(),object};}}}return nearest;}

test('packed two-level native triangle query matches independent brute triangles through rotated/scaled instances',async()=>{
 const f=fixture(),atlas=await createNativeHitGeometry({THREE,scene:f.scene,objects:f.objects,ductObject:f.duct,yieldBuild:async()=>{}});let seed=773;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);
 for(let i=0;i<320;i++){const origin=[(random()-.5)*40,(random()-.5)*40,15+random()*20],target=[(random()-.5)*20,(random()-.5)*16,(random()-.5)*14],direction=new THREE.Vector3(...target).sub(new THREE.Vector3(...origin)).normalize().toArray(),minimum=i%9===0?2:.001,maximum=i%7===0?20:100;
  const actual=atlas.intersectRay(origin,direction,{minDistance:minimum,maxDistance:maximum}),expected=brute(f.objects.slice(0,3),origin,direction,minimum,maximum);assert.equal(!!actual,!!expected);if(expected){close(actual.distance,expected.distance,2e-5);assert.equal(actual.object,expected.object);for(let j=0;j<3;j++)close(actual.point[j],expected.point[j],2e-5);}
  const duct=atlas.intersectRay(origin,direction,{classFilter:1,minDistance:minimum,maxDistance:maximum}),ductExpected=brute([f.duct],origin,direction,minimum,maximum);assert.equal(!!duct,!!ductExpected);if(ductExpected){close(duct.distance,ductExpected.distance,2e-5);assert.equal(duct.classTag,1);}
 }
 assert.equal(atlas.snapshot().opaqueInstances,3);assert.equal(atlas.snapshot().ductInstances,1);assert.ok(atlas.snapshot().bvhStackDepth<=64);assert.equal(atlas.snapshot().textureSamplers,9);atlas.dispose();
});
test('source indexed CAD and material assignments remain intact through BVH ordering and current pose updates',async()=>{
 const f=fixture(),sourcePositions=f.objects[2].geometry.attributes.position.array.slice(),sourceIndex=f.objects[2].geometry.index.array.slice(),atlas=await createNativeHitGeometry({THREE,scene:f.scene,objects:f.objects,yieldBuild:async()=>{}}),record=atlas.records.find(value=>value.object===f.objects[2]);
 assert.deepEqual(f.objects[2].geometry.attributes.position.array,sourcePositions);assert.deepEqual(f.objects[2].geometry.index.array,sourceIndex);assert.deepEqual(f.objects[2].geometry.groups.map(group=>group.materialIndex),[0,1,2,3,4,5]);
 for(let i=0;i<record.triangleCount;i++){const original=record.order[i],material=f.objects[2].material[Math.floor(original/2)],id=atlas.triangles.data[(record.triangleOffset+i)*4+3];assert.equal(atlas.materials[id],material);}
 const before=atlas.snapshot();f.objects[0].position.y+=4;atlas.update();assert.equal(atlas.snapshot().refits,before.refits);assert.equal(atlas.snapshot().tlasUpdates,before.tlasUpdates+1);
 const origin=[-7,4,30],direction=[0,0,-1],expected=brute(f.objects.slice(0,3),origin,direction);close(atlas.intersectRay(origin,direction).distance,expected.distance);f.objects[0].visible=false;atlas.update();assert.equal(atlas.intersectRay(origin,direction),null);atlas.dispose();
});
test('real deformed cable vertices refit their own BLAS and upload only their atlas ranges',async()=>{
 const scene=new THREE.Scene(),material=new THREE.MeshPhysicalMaterial(),cable=new THREE.Mesh(new THREE.BoxGeometry(2,2,4),material),fixed=new THREE.Mesh(new THREE.BoxGeometry(3,3,3),material);fixed.position.x=20;scene.add(cable,fixed);
 const atlas=await createNativeHitGeometry({THREE,scene,objects:[fixed],cableMeshes:[cable],yieldBuild:async()=>{}}),record=atlas.records.find(value=>value.object===cable),vertex=cable.geometry.attributes.position;for(const uniform of Object.values(atlas.uniforms))uniform.value.onUpdate?.();for(let i=0;i<vertex.count;i++)vertex.setZ(i,vertex.getZ(i)+3);vertex.needsUpdate=true;atlas.update();close(atlas.intersectRay([0,0,20],[0,0,-1]).distance,15);assert.equal(atlas.snapshot().refits,1);
 assert.equal(atlas.positions.texture.updateRanges[0].start,record.vertexOffset*4);assert.equal(atlas.positions.texture.updateRanges.reduce((sum,range)=>sum+range.count,0),record.vertexCount*4);assert.deepEqual(fixed.geometry.attributes.position.array,new THREE.BoxGeometry(3,3,3).attributes.position.array);atlas.dispose();
});
test('authored normals preserve poles and seams; disposal releases all owned resources once',async()=>{
 for(const normal of[[0,0,-1],[0,0,1],[-1,0,0],[0,-1,0],[.3,-.4,-.7]]){const expected=new THREE.Vector3(...normal).normalize(),actual=new THREE.Vector3(...decodeHitNormal(encodeHitNormal(normal)));assert.ok(actual.distanceTo(expected)<1e-12);}
 const f=fixture(),atlas=await createNativeHitGeometry({THREE,scene:f.scene,objects:f.objects,yieldBuild:async()=>{}});let disposals=0;for(const uniform of Object.values(atlas.uniforms))uniform.value.addEventListener('dispose',()=>disposals++);atlas.dispose();atlas.dispose();assert.equal(disposals,9);assert.equal(atlas.intersectRay([0,0,30],[0,0,-1]),null);assert.equal(atlas.snapshot().sourceGeometryChanged,false);
 const glsl=nativeHitGeometryGLSL({tlasOffset:20,maxDepth:10});assert.match(glsl,/cadVertexVisibility\(uint vertex\)/);assert.match(glsl,/transpose\(mat3\(inverse\)\)/);assert.ok(!glsl.includes('cadOpaqueDepth'));assert.ok(!glsl.includes('getTransmissionSample'));
});

test('shared indexed PBR/source boundaries keep both authored attribute representations and real occlusion',async()=>{
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([-1,-1,0,1,-1,0,1,1,0,-1,1,0],3));geometry.setIndex([0,1,2,0,2,3]);geometry.addGroup(0,3,0);geometry.addGroup(3,3,1);geometry.computeVertexNormals();geometry.setAttribute('metalUv',new THREE.Float32BufferAttribute([.11,.12,.21,.22,.31,.32,.41,.42],2));geometry.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,1,1,0,1],2));geometry.setAttribute('finish',new THREE.Float32BufferAttribute([.81,.91,.82,.92,.83,.93,.84,.94],2));geometry.setAttribute('occlusion',new THREE.Float32BufferAttribute([.3,.4,.5,.6],1));
 const pbr=new THREE.MeshPhysicalMaterial(),source=new THREE.MeshPhysicalMaterial();pbr.userData.pbrMetal={};source.userData.secondarySourceFinish=true;const object=new THREE.Mesh(geometry,[pbr,source]),scene=new THREE.Scene();scene.add(object);const original=geometry.index.array.slice(),atlas=await createNativeHitGeometry({THREE,scene,objects:[object],yieldBuild:async()=>{}}),record=atlas.records[0];assert.equal(record.vertexCount,6);assert.deepEqual(geometry.index.array,original);
 for(let triangle=0;triangle<record.triangleCount;triangle++){const at=(record.triangleOffset+triangle)*4,id=atlas.triangles.data[at+3],isPbr=atlas.materials[id]===pbr;for(let k=0;k<3;k++){const vertex=atlas.triangles.data[at+k],sourceVertex=record.sourceVertices[vertex-record.vertexOffset];close(atlas.positions.data[vertex*4+3],geometry.attributes.occlusion.getX(sourceVertex));const expected=isPbr?geometry.attributes.metalUv:geometry.attributes.finish;close(atlas.attributes[2].data[vertex*4],expected.getX(sourceVertex));close(atlas.attributes[2].data[vertex*4+1],expected.getY(sourceVertex));}}
 atlas.dispose();geometry.deleteAttribute('finish');source.userData.secondarySourceFinish=false;const protectedAtlas=await createNativeHitGeometry({THREE,scene,objects:[object],yieldBuild:async()=>{}});for(let i=0;i<protectedAtlas.records[0].vertexCount;i++)if(protectedAtlas.records[0].vertexMaterials[i]===source){assert.equal(protectedAtlas.attributes[2].data[i*4],1);assert.equal(protectedAtlas.attributes[2].data[i*4+1],1);}protectedAtlas.dispose();
});

test('Float32 rays on native-sized shared CAD edges cannot fall through both adjacent triangles',()=>{
 const a=[-26.3,-15.58,-12.08],b=[26.3,-15.58,-12.08],c=[26.3,-6.1138,-.8751],d=[-26.3,-6.1138,-.8751],normal=new THREE.Vector3().crossVectors(new THREE.Vector3(...b).sub(new THREE.Vector3(...a)),new THREE.Vector3(...c).sub(new THREE.Vector3(...a))).normalize();
 for(let i=1;i<200;i++){const u=i/200,point=a.map((v,k)=>v*(1-u)+c[k]*u),direction=normal.clone().negate().add(new THREE.Vector3(.137,.059,.021)).normalize().toArray(),origin=point.map((v,k)=>Math.fround(v-direction[k]*350)),r0=intersectHitTriangleFloat32(origin,direction,a,b,c),r1=intersectHitTriangleFloat32(origin,direction,a,c,d);assert.ok(r0||r1,`shared edge gap at ${u}`);close((r0??r1).distance,350,1e-3);close((r0??r1).bary.reduce((s,v)=>s+v,0),1,1e-12);}
 assert.equal(intersectHitTriangleFloat32([0,100,100],[0,0,-1],a,b,c),null);assert.equal(intersectHitTriangleFloat32([0,0,1],[0,0,-1],[-1,-1,0],[1,-1,0],[0,1,0],{maxDistance:.5}),null);
});


test('native atlas first upload includes every BLAS; subsequent ranges are row-safe exact authored components with fresh versions',async()=>{
 const f=fixture(),atlas=await createNativeHitGeometry({THREE,scene:f.scene,objects:f.objects,ductObject:f.duct,yieldBuild:async()=>{}});
 for(const uniform of Object.values(atlas.uniforms)){assert.equal(uniform.value.userData.nativeAtlasUploadComplete,false);assert.deepEqual(uniform.value.updateRanges,[],'Initial GPU storage receives every texel, including BLAS prefix');uniform.value.onUpdate();assert.equal(uniform.value.userData.nativeAtlasUploadComplete,true);}
 const before=new Map(Object.values(atlas.uniforms).map(uniform=>[uniform.value,uniform.value.version]));f.objects[0].position.y+=3;const positions=f.objects[1].geometry.attributes.position;for(let i=0;i<positions.count;i++)positions.setZ(i,positions.getZ(i)+.25);positions.needsUpdate=true;atlas.update();
 for(const value of[atlas.positions,...atlas.attributes,atlas.bounds,atlas.contents]){const texture=value.texture;assert.ok(texture.version>before.get(texture));for(const range of texture.updateRanges){assert.equal(range.start%4,0);assert.equal(range.count%4,0);assert.ok(range.start>=0&&range.start+range.count<=value.data.length);assert.equal(Math.floor(range.start/(texture.image.width*4)),Math.floor((range.start+range.count-1)/(texture.image.width*4)),'Each DataTexture range fits exactly one row');}}
 const moved=atlas.records.find(record=>record.object===f.objects[1]),vertexRanges=atlas.positions.texture.updateRanges;assert.equal(vertexRanges[0].start,moved.vertexOffset*4);assert.equal(vertexRanges.reduce((sum,range)=>sum+range.count,0),moved.vertexCount*4);assert.ok(atlas.bounds.texture.updateRanges.length>1,'Large changed tree bounds are split rather than sent as one invalid row');atlas.dispose();
});


test('curved native vertex normals recover the authored smooth Snell direction while geometric normals retain crossing classification',async()=>{
 const f=fixture(),atlas=await createNativeHitGeometry({THREE,scene:f.scene,objects:f.objects,yieldBuild:async()=>{}}),direction=[0,0,-1],hit=atlas.intersectRay([7.3,2.7,14],direction),sphere=f.objects[1];assert.equal(hit.object,sphere);const expectedNormal=new THREE.Vector3(...hit.localPosition).normalize().toArray(),smooth=nativeDielectric(direction,hit.normal,1,1.52),expected=nativeDielectric(direction,expectedNormal,1,1.52),facet=nativeDielectric(direction,hit.geometricNormal,1,1.52);
 assert.ok(new THREE.Vector3(...hit.normal).distanceTo(new THREE.Vector3(...expectedNormal))<1e-6);assert.ok(new THREE.Vector3(...smooth.direction).distanceTo(new THREE.Vector3(...expected.direction))<1e-6);assert.ok(new THREE.Vector3(...facet.direction).distanceTo(new THREE.Vector3(...expected.direction))>.005,'Using planar tessellation normals creates a visibly different refraction');assert.ok(hit.geometricNormal.reduce((sum,value,i)=>sum+value*direction[i],0)<0);assert.ok(hit.normal.reduce((sum,value,i)=>sum+value*hit.geometricNormal[i],0)>0);atlas.dispose();
});
