"""General low-dimensional inverse rendering using checked scene parameters.

This is finite-difference optimization, NOT general automatic differentiation.
Finite differences rerun visibility and sampling, but have step-size bias and can
have high variance. Native material/shader AD is a separate, narrower facility.
Every forward image here is generated by the real C++ renderer.
"""
from __future__ import annotations
from dataclasses import dataclass, asdict
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Callable, Sequence
import contextlib
import io
import json
import math
import numpy as np
from . import Scene, render, read_pfm, traverse
from .workflow import validate_scene

@dataclass(frozen=True)
class Parameter:
    key: str
    component: int|None=None
    step: float=0.01
    lower: float=-math.inf
    upper: float=math.inf

    def __post_init__(self):
        if not math.isfinite(self.step) or self.step<=0 or math.isnan(self.lower) or math.isnan(self.upper) or self.lower>=self.upper:
            raise ValueError('Parameter requires a positive finite difference step and ordered bounds')
        if self.component is not None and (not isinstance(self.component,int) or self.component<0):raise ValueError('Vector component cannot be negative')


def values(scene: Scene, parameters: Sequence[Parameter])->np.ndarray:
    mapping=traverse(scene);result=[]
    for parameter in parameters:
        value=mapping[parameter.key]
        if parameter.component is not None:value=value[parameter.component]
        if not np.isscalar(value) or not np.isfinite(value):raise ValueError('Optimization variables must select finite numeric scalars')
        if not parameter.lower<=float(value)<=parameter.upper:raise ValueError('Initial value lies outside its bounds')
        result.append(float(value))
    return np.asarray(result)


def apply(scene: Scene, parameters: Sequence[Parameter], vector: np.ndarray)->Scene:
    if len(parameters)!=len(vector) or not np.isfinite(vector).all():raise ValueError('Invalid optimization vector')
    candidate=scene.clone();mapping=traverse(candidate)
    for parameter,value in zip(parameters,vector):
        if not parameter.lower<=value<=parameter.upper:raise ValueError('Optimization value lies outside its bounds')
        if parameter.component is None:mapping[parameter.key]=float(value)
        else:
            current=list(mapping[parameter.key]);current[parameter.component]=float(value);mapping[parameter.key]=current
    mapping.update();return candidate


def gaussian_objective_filter(image: np.ndarray,sigma: float=0.)->np.ndarray:
    """A declared loss filter. Display images are never modified by this helper."""
    if sigma==0:return image
    if not math.isfinite(sigma) or sigma<0:raise ValueError('Loss blur sigma must be finite and nonnegative')
    radius=max(1,int(math.ceil(3*sigma)));positions=np.arange(-radius,radius+1)
    kernel=np.exp(-positions**2/(2*sigma*sigma));kernel/=kernel.sum();out=np.asarray(image,dtype=float)
    for axis in (0,1):
        pad=[(0,0)]*out.ndim;pad[axis]=(radius,radius);padded=np.pad(out,pad,mode='edge');result=np.zeros_like(out)
        for index,weight in enumerate(kernel):
            slices=[slice(None)]*out.ndim;slices[axis]=slice(index,index+out.shape[axis]);result+=weight*padded[tuple(slices)]
        out=result
    return out


def optimize(scene: Scene,target: np.ndarray,parameters: Sequence[Parameter],*,
             max_iterations: int=15,loss_blur_sigma: float=0.,initial_damping: float=1e-2,
             executable: str|Path|None=None,progress: Callable[[dict],None]|None=None,
             output_directory: str|Path|None=None)->tuple[Scene,dict]:
    """Bounded Levenberg–Marquardt with a central/one-sided finite-difference Jacobian.

    Parameters include geometry, camera, materials, lights, and volume controls
    exposed by traverse(). It is intended for a modest number of scalar controls,
    not millions of vertices/texels. Common random numbers reduce differences in
    the Monte Carlo objective; they do not remove finite-sampling bias or prove
    visibility-aware AD. No reference images are copied into the renderer.
    """
    validate_scene(scene);target=np.asarray(target,dtype=float);parameters=list(parameters)
    if not parameters or max_iterations<1 or initial_damping<=0:raise ValueError('Invalid optimizer configuration')
    if target.shape!=(scene.settings.height,scene.settings.width,3) or not np.isfinite(target).all():raise ValueError('Target must match the finite raw RGB film')
    if len({(p.key,p.component) for p in parameters})!=len(parameters):raise ValueError('Duplicate optimization variables')
    base=scene.clone();base.settings.ad=False
    target_residual=gaussian_objective_filter(target,loss_blur_sigma).ravel()
    vector=values(base,parameters);lower=np.array([p.lower for p in parameters]);upper=np.array([p.upper for p in parameters])
    history=[];evaluations=0;damping=initial_damping;reason='iteration_limit'
    with TemporaryDirectory(prefix='cybr-inverse-') as temporary:
        directory=Path(temporary)
        def evaluate(x):
            nonlocal evaluations
            candidate=apply(base,parameters,x)
            prefix=directory/'forward'
            # All calls use the unchanged scene seed; only explicitly selected
            # scalar scene parameters differ between finite-difference evaluations.
            render(candidate,prefix,executable=executable)
            image=read_pfm(prefix.with_suffix('.pfm')).astype(float);evaluations+=1
            return gaussian_objective_filter(image,loss_blur_sigma).ravel()-target_residual,image
        residual,image=evaluate(vector);loss=float(np.mean(residual*residual));initial_loss=loss
        for iteration in range(max_iterations):
            jacobian=np.empty((residual.size,len(vector)))
            for j,parameter in enumerate(parameters):
                minus=vector.copy();plus=vector.copy()
                minus[j]=max(lower[j],vector[j]-parameter.step);plus[j]=min(upper[j],vector[j]+parameter.step)
                interval=plus[j]-minus[j]
                if interval<=0:raise ValueError('No finite-difference interval inside bounds')
                rm,_=evaluate(minus);rp,_=evaluate(plus);jacobian[:,j]=(rp-rm)/interval
            gram=jacobian.T@jacobian/residual.size;gradient=jacobian.T@residual/residual.size
            scale=np.maximum(np.diag(gram),1e-12)
            accepted=False;previous_loss=loss;delta=np.zeros_like(vector)
            for retry in range(7):
                try:delta=np.linalg.solve(gram+damping*np.diag(scale),-gradient)
                except np.linalg.LinAlgError:damping*=10;continue
                candidate=np.clip(vector+delta,lower,upper)
                try:trial_residual,trial_image=evaluate(candidate)
                except (ValueError,RuntimeError):damping*=10;continue
                trial_loss=float(np.mean(trial_residual*trial_residual))
                if trial_loss<loss:
                    vector=candidate;residual=trial_residual;image=trial_image;loss=trial_loss;damping=max(1e-9,damping*.4);accepted=True;break
                damping*=8
            record={'iteration':iteration,'values':vector.tolist(),'mean_squared_loss':loss,
                    'accepted':accepted,'damping':damping,'gradient_norm':float(np.linalg.norm(gradient))}
            history.append(record)
            if progress:progress(record)
            if not accepted:reason='no_improving_step';break
            if np.linalg.norm(delta)<1e-7:reason='small_step';break
            if abs(previous_loss-loss)<1e-12:reason='small_loss_change';break
    result=apply(base,parameters,vector)
    report={'algorithm':'bounded LM with rerendered finite-difference Jacobian','automatic_differentiation':False,
            'visibility':'forward visibility reruns; no claim of unbiased visibility derivatives',
            'finite_difference_steps':[p.step for p in parameters],'parameters':[p.key+('' if p.component is None else f'[{p.component}]') for p in parameters],
            'initial_values':values(base,parameters).tolist(),'final_values':vector.tolist(),
            'initial_loss':initial_loss,'final_loss':loss,'loss_blur_sigma_pixels':loss_blur_sigma,
            'common_random_numbers':True,'seed':base.settings.seed,'forward_evaluations':evaluations,
            'termination':reason,'history':history}
    if output_directory:
        output_directory=Path(output_directory);output_directory.mkdir(parents=True,exist_ok=True)
        (output_directory/'optimization.json').write_text(json.dumps(report,indent=2))
        from .workflow import bundle_scene
        bundle_scene(result,output_directory/'final_scene')
        render(result,output_directory/'fitted',executable=executable)
    return result,report
